#!/bin/sh
# Gradle wrapper script
# Generated by Gradle

# Attempt to set APP_HOME
APP_HOME=`dirname "$0"`
APP_HOME=`cd "$APP_HOME" && pwd`

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS=""

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
}

die () {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
case "`uname`" in
  CYGWIN* ) cygwin=true ;;
  Darwin* ) darwin=true ;;
esac

# For Cygwin, ensure paths are in UNIX format before anything is touched.
if $cygwin ; then
    [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
fi

# Attempt to find Java
if [ -z "$JAVA_HOME" ] ; then
    JAVACMD=`which java`
    if [ -n "$JAVACMD" ] ; then
        JAVA_HOME=`dirname "$JAVACMD"`/..
    fi
else
    JAVACMD="$JAVA_HOME/bin/java"
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" -a "$darwin" = "false" ] ; then
    MAX_FD=`ulimit -H -n`
    if [ $? -eq 0 ] ; then
        ulimit -n $MAX_FD
    fi
fi

# Setup the classpath
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Execute Gradle
exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain "$@"
