org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+UseG1GC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=false

android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2048m

org.jetbrains.compose.experimental.jscan=true
# 最高优先级锁定Compose编译器版本
androidx.compose.compiler.version=1.5.14
android.enableR8.fullMode=true
